// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: WhetherLCD

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_LCY;
lv_obj_t * ui_LableWhether;
lv_obj_t * ui_ImgWhether;
lv_obj_t * ui_LCW;
lv_obj_t * ui_LableTime;
lv_obj_t * ui_LableChineseMonth;
lv_obj_t * ui_LableChineseDay;
lv_obj_t * ui_LCDate;
lv_obj_t * ui_LableWeek;
lv_obj_t * ui_LCM;
lv_obj_t * ui_LCD;
lv_obj_t * ui_LableTime1;
lv_obj_t * ui_LableTime2;
lv_obj_t * ui_LableTime3;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1827161042[1] = {&ui_img_1733488461};
const lv_img_dsc_t * ui_imgset_1445304015[1] = {&ui_img_1532110541};
const lv_img_dsc_t * ui_imgset_1813959690[4] = {&ui_img_261581757, &ui_img_820147422, &ui_img_583279387, &ui_img_2018655616};
const lv_img_dsc_t * ui_imgset_2070076777[2] = {&ui_img_273823832, &ui_img_807905347};
const lv_img_dsc_t * ui_imgset_1752351987[2] = {&ui_img_58911356, &ui_img_1022817823};
const lv_img_dsc_t * ui_imgset_1994559363[3] = {&ui_img_997974308, &ui_img_83754871, &ui_img_1165484050};
const lv_img_dsc_t * ui_imgset_bg[1] = {&ui_img_bg3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
