// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: WhetherLCD

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_bg3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Screen1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LCY = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LCY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LCY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LCY, -52);
    lv_obj_set_y(ui_LCY, -95);
    lv_obj_set_align(ui_LCY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LCY, "年");
    lv_obj_set_style_text_color(ui_LCY, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LCY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LCY, &ui_font_Jianti32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableWhether = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LableWhether, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableWhether, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableWhether, 52);
    lv_obj_set_y(ui_LableWhether, -45);
    lv_obj_set_align(ui_LableWhether, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableWhether, "晴");
    lv_obj_set_style_text_color(ui_LableWhether, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableWhether, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableWhether, &ui_font_Jianti32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgWhether = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImgWhether, &ui_img_whether_sun_png);
    lv_obj_set_width(ui_ImgWhether, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgWhether, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgWhether, -63);
    lv_obj_set_y(ui_ImgWhether, -34);
    lv_obj_set_align(ui_ImgWhether, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWhether, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWhether, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LCW = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LCW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LCW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LCW, -77);
    lv_obj_set_y(ui_LCW, 23);
    lv_obj_set_align(ui_LCW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LCW, "星期");
    lv_obj_set_style_text_color(ui_LCW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LCW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LCW, &ui_font_Jianti32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LableTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableTime, -1);
    lv_obj_set_y(ui_LableTime, 85);
    lv_obj_set_align(ui_LableTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableTime, "88:88:88");
    lv_obj_set_style_text_color(ui_LableTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableChineseMonth = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LableChineseMonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableChineseMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableChineseMonth, 74);
    lv_obj_set_y(ui_LableChineseMonth, 12);
    lv_obj_set_align(ui_LableChineseMonth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableChineseMonth, "润五月");
    lv_obj_set_style_text_color(ui_LableChineseMonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableChineseMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableChineseMonth, &ui_font_Jianti24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableChineseDay = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LableChineseDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableChineseDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableChineseDay, 75);
    lv_obj_set_y(ui_LableChineseDay, 45);
    lv_obj_set_align(ui_LableChineseDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableChineseDay, "三十一");
    lv_obj_set_style_text_color(ui_LableChineseDay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableChineseDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableChineseDay, &ui_font_Jianti24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LCDate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LCDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LCDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LCDate, 22);
    lv_obj_set_y(ui_LCDate, 28);
    lv_obj_set_align(ui_LCDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LCDate, "农\n历");
    lv_obj_set_style_text_color(ui_LCDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LCDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LCDate, &ui_font_Jianti24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableWeek = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LableWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableWeek, -28);
    lv_obj_set_y(ui_LableWeek, 22);
    lv_obj_set_align(ui_LableWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableWeek, "六");
    lv_obj_set_style_text_color(ui_LableWeek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableWeek, &ui_font_Jianti32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LCM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LCM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LCM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LCM, 25);
    lv_obj_set_y(ui_LCM, -95);
    lv_obj_set_align(ui_LCM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LCM, "月");
    lv_obj_set_style_text_color(ui_LCM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LCM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LCM, &ui_font_Jianti32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LCD = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LCD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LCD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LCD, 93);
    lv_obj_set_y(ui_LCD, -95);
    lv_obj_set_align(ui_LCD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LCD, "日");
    lv_obj_set_style_text_color(ui_LCD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LCD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LCD, &ui_font_Jianti32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableTime1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LableTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableTime1, -90);
    lv_obj_set_y(ui_LableTime1, -95);
    lv_obj_set_align(ui_LableTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableTime1, "88");
    lv_obj_set_style_text_color(ui_LableTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableTime1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableTime2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LableTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableTime2, -13);
    lv_obj_set_y(ui_LableTime2, -95);
    lv_obj_set_align(ui_LableTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableTime2, "88");
    lv_obj_set_style_text_color(ui_LableTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableTime2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableTime3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LableTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableTime3, 60);
    lv_obj_set_y(ui_LableTime3, -95);
    lv_obj_set_align(ui_LableTime3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableTime3, "88");
    lv_obj_set_style_text_color(ui_LableTime3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableTime3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableTime3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

}
