// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: WhetherLCD

#ifndef _WHETHERLCD_UI_H
#define _WHETHERLCD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LCY;
extern lv_obj_t * ui_LableWhether;
extern lv_obj_t * ui_ImgWhether;
extern lv_obj_t * ui_LCW;
extern lv_obj_t * ui_LableTime;
extern lv_obj_t * ui_LableChineseMonth;
extern lv_obj_t * ui_LableChineseDay;
extern lv_obj_t * ui_LCDate;
extern lv_obj_t * ui_LableWeek;
extern lv_obj_t * ui_LCM;
extern lv_obj_t * ui_LCD;
extern lv_obj_t * ui_LableTime1;
extern lv_obj_t * ui_LableTime2;
extern lv_obj_t * ui_LableTime3;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bg3_png);    // assets\bg3.png
LV_IMG_DECLARE(ui_img_whether_sun_png);    // assets\Whether\Sun.png
LV_IMG_DECLARE(ui_img_1733488461);    // assets\Whether\Night--rainy-2.png
LV_IMG_DECLARE(ui_img_1532110541);    // assets\Whether\Night-rainy-3.png
LV_IMG_DECLARE(ui_img_261581757);    // assets\Whether\Rainy-2.png
LV_IMG_DECLARE(ui_img_820147422);    // assets\Whether\Rainy-3.png
LV_IMG_DECLARE(ui_img_583279387);    // assets\Whether\Rainy-4.png
LV_IMG_DECLARE(ui_img_2018655616);    // assets\Whether\Rainy-5.png
LV_IMG_DECLARE(ui_img_273823832);    // assets\Whether\Snowflake-2.png
LV_IMG_DECLARE(ui_img_807905347);    // assets\Whether\Snowflake-3.png
LV_IMG_DECLARE(ui_img_58911356);    // assets\Whether\Sunhine-rainy-2.png
LV_IMG_DECLARE(ui_img_1022817823);    // assets\Whether\Sunhine-rainy-3.png
LV_IMG_DECLARE(ui_img_997974308);    // assets\Whether\Thermometer-2.png
LV_IMG_DECLARE(ui_img_83754871);    // assets\Whether\Thermometer-3.png
LV_IMG_DECLARE(ui_img_1165484050);    // assets\Whether\Thermometer-4.png

LV_FONT_DECLARE(ui_font_Jianti16);
LV_FONT_DECLARE(ui_font_Jianti24);
LV_FONT_DECLARE(ui_font_Jianti32);
LV_FONT_DECLARE(ui_font_Jianti48);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
