// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: WhetherLCD

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_LCY;
lv_obj_t * ui_LableWhether;
lv_obj_t * ui_ImgWhether;
lv_obj_t * ui_LCW;
lv_obj_t * ui_LableHour;
lv_obj_t * ui_LableChineseMonth;
lv_obj_t * ui_LableChineseDay;
lv_obj_t * ui_LCDate;
lv_obj_t * ui_LableWeek;
lv_obj_t * ui_LCM;
lv_obj_t * ui_LCD;
lv_obj_t * ui_LableTimeYear;
lv_obj_t * ui_LableTimeMonth;
lv_obj_t * ui_LableTimeDate;
lv_obj_t * ui_LableMin;
lv_obj_t * ui_LableSec;
lv_obj_t * ui_LCT;
lv_obj_t * ui_LCT1;
lv_obj_t * ui_LableTempHi;
lv_obj_t * ui_LableTempLo;
lv_obj_t * ui_LableDASH;
lv_obj_t * ui_LableUNIT;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_bg[2] = {&ui_img_bg0_png, &ui_img_bg3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
