// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: WhetherLCD

#ifndef _WHETHERLCD_UI_H
#define _WHETHERLCD_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
    // SCREEN: ui_Screen1
    void ui_Screen1_screen_init(void);
    extern lv_obj_t *ui_Screen1;
    extern lv_obj_t *ui_LCY;
    extern lv_obj_t *ui_LableWhether;
    extern lv_obj_t *ui_ImgWhether;
    extern lv_obj_t *ui_LCW;
    extern lv_obj_t *ui_LableHour;
    extern lv_obj_t *ui_LableChineseMonth;
    extern lv_obj_t *ui_LableChineseDay;
    extern lv_obj_t *ui_LCDate;
    extern lv_obj_t *ui_LableWeek;
    extern lv_obj_t *ui_LCM;
    extern lv_obj_t *ui_LCD;
    extern lv_obj_t *ui_LableTimeYear;
    extern lv_obj_t *ui_LableTimeMonth;
    extern lv_obj_t *ui_LableTimeDate;
    extern lv_obj_t *ui_LableMin;
    extern lv_obj_t *ui_LableSec;
    extern lv_obj_t *ui_LCT;
    extern lv_obj_t *ui_LCT1;
    extern lv_obj_t *ui_LableTempHi;
    extern lv_obj_t *ui_LableTempLo;
    extern lv_obj_t *ui_LableDASH;
    extern lv_obj_t *ui_LableUNIT;
    extern lv_obj_t *ui____initial_actions0;

    LV_FONT_DECLARE(ui_font_Jianti16);
    LV_FONT_DECLARE(ui_font_Jianti24);
    LV_FONT_DECLARE(ui_font_Jianti32);
    LV_FONT_DECLARE(ui_font_Jianti48);
    LV_IMG_DECLARE(ui_img_bg0_png);    // assets\bg0.png
    LV_IMG_DECLARE(ui_img_bg3_png);    // assets\bg3.png
    LV_IMG_DECLARE(ui_img_1596713459); // IMAGE DATA: assets\white\0@2x.png
    LV_IMG_DECLARE(ui_img_1768248264); // IMAGE DATA: assets\white\1@2x.png
    LV_IMG_DECLARE(ui_img_157055255);  // IMAGE DATA: assets\white\2@2x.png
    LV_IMG_DECLARE(ui_img_712580050);  // IMAGE DATA: assets\white\3@2x.png
    LV_IMG_DECLARE(ui_img_1936254497); // IMAGE DATA: assets\white\4@2x.png
    LV_IMG_DECLARE(ui_img_1006248924); // IMAGE DATA: assets\white\5@2x.png
    LV_IMG_DECLARE(ui_img_604944085);  // IMAGE DATA: assets\white\6@2x.png
    LV_IMG_DECLARE(ui_img_49419290);   // IMAGE DATA: assets\white\7@2x.png
    LV_IMG_DECLARE(ui_img_72714779);   // IMAGE DATA: assets\white\8@2x.png
    LV_IMG_DECLARE(ui_img_1002720352); // IMAGE DATA: assets\white\9@2x.png
    LV_IMG_DECLARE(ui_img_1720731786); // IMAGE DATA: assets\white\10@2x.png
    LV_IMG_DECLARE(ui_img_1720837355); // IMAGE DATA: assets\white\11@2x.png
    LV_IMG_DECLARE(ui_img_1720799304); // IMAGE DATA: assets\white\12@2x.png
    LV_IMG_DECLARE(ui_img_1720905129); // IMAGE DATA: assets\white\13@2x.png
    LV_IMG_DECLARE(ui_img_1720875278); // IMAGE DATA: assets\white\14@2x.png
    LV_IMG_DECLARE(ui_img_1720980847); // IMAGE DATA: assets\white\15@2x.png
    LV_IMG_DECLARE(ui_img_1720942796); // IMAGE DATA: assets\white\16@2x.png
    LV_IMG_DECLARE(ui_img_1721048621); // IMAGE DATA: assets\white\17@2x.png
    LV_IMG_DECLARE(ui_img_1721018770); // IMAGE DATA: assets\white\18@2x.png
    LV_IMG_DECLARE(ui_img_1721124339); // IMAGE DATA: assets\white\19@2x.png
    LV_IMG_DECLARE(ui_img_1793650149); // IMAGE DATA: assets\white\20@2x.png
    LV_IMG_DECLARE(ui_img_1793755718); // IMAGE DATA: assets\white\21@2x.png
    LV_IMG_DECLARE(ui_img_1793717667); // IMAGE DATA: assets\white\22@2x.png
    LV_IMG_DECLARE(ui_img_1793823492); // IMAGE DATA: assets\white\23@2x.png
    LV_IMG_DECLARE(ui_img_1793793641); // IMAGE DATA: assets\white\24@2x.png
    LV_IMG_DECLARE(ui_img_1793899210); // IMAGE DATA: assets\white\25@2x.png
    LV_IMG_DECLARE(ui_img_1793861159); // IMAGE DATA: assets\white\26@2x.png
    LV_IMG_DECLARE(ui_img_1793966984); // IMAGE DATA: assets\white\27@2x.png
    LV_IMG_DECLARE(ui_img_1793937133); // IMAGE DATA: assets\white\28@2x.png
    LV_IMG_DECLARE(ui_img_1794042702); // IMAGE DATA: assets\white\29@2x.png
    LV_IMG_DECLARE(ui_img_775672896);  // IMAGE DATA: assets\white\30@2x.png
    LV_IMG_DECLARE(ui_img_775567327);  // IMAGE DATA: assets\white\31@2x.png
    LV_IMG_DECLARE(ui_img_775605378);  // IMAGE DATA: assets\white\32@2x.png
    LV_IMG_DECLARE(ui_img_775499553);  // IMAGE DATA: assets\white\33@2x.png
    LV_IMG_DECLARE(ui_img_775529404);  // IMAGE DATA: assets\white\34@2x.png
    LV_IMG_DECLARE(ui_img_775423835);  // IMAGE DATA: assets\white\35@2x.png
    LV_IMG_DECLARE(ui_img_775461886);  // IMAGE DATA: assets\white\36@2x.png
    LV_IMG_DECLARE(ui_img_775356061);  // IMAGE DATA: assets\white\37@2x.png
    LV_IMG_DECLARE(ui_img_775385912);  // IMAGE DATA: assets\white\38@2x.png
    LV_IMG_DECLARE(ui_img_710175435);  // IMAGE DATA: assets\white\99@2x.png

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
