// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: WhetherLCD

#ifndef _WHETHERLCD_UI_H
#define _WHETHERLCD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LCY;
extern lv_obj_t * ui_LableWhether;
extern lv_obj_t * ui_ImgWhether;
extern lv_obj_t * ui_LCW;
extern lv_obj_t * ui_LableHour;
extern lv_obj_t * ui_LableChineseMonth;
extern lv_obj_t * ui_LableChineseDay;
extern lv_obj_t * ui_LCDate;
extern lv_obj_t * ui_LableWeek;
extern lv_obj_t * ui_LCM;
extern lv_obj_t * ui_LCD;
extern lv_obj_t * ui_LableTimeYear;
extern lv_obj_t * ui_LableTimeMonth;
extern lv_obj_t * ui_LableTimeDate;
extern lv_obj_t * ui_LableMin;
extern lv_obj_t * ui_LableSec;
extern lv_obj_t * ui_LCT;
extern lv_obj_t * ui_LCT1;
extern lv_obj_t * ui_LableTempHi;
extern lv_obj_t * ui_LableTempLo;
extern lv_obj_t * ui_LableDASH;
extern lv_obj_t * ui_LableUNIT;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bg3_png);    // assets\bg3.png
LV_IMG_DECLARE(ui_img_day_sunny_1000_png);    // assets\Day_Sunny_1000.png
LV_IMG_DECLARE(ui_img_bg0_png);    // assets\bg0.png

LV_FONT_DECLARE(ui_font_Jianti16);
LV_FONT_DECLARE(ui_font_Jianti24);
LV_FONT_DECLARE(ui_font_Jianti32);
LV_FONT_DECLARE(ui_font_Jianti48);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
